services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:15.2
    volumes:
      - postgres_data_keep_going:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_keep_going:
